
## Variable-level P values

Your go-to test for getting variable-level P values is `anova`

`drop1` is a wrapper that allows you to do many simple anovas at once (one for each variable (or term) that R thinks it should drop).

When you are *estimating* variance (e.g., with a normal response variable) you should use an $F$ test.

When you can *calculate* variance from your assumptions (e.g., with a Poisson or binomial), you should use a $\chi^2$ test.

```{r}
load("data/contrasts2.RData")
print(summary(lmTL1))
 lmlight <- lm(grahami~light, data=lizards)
 lmtime <- lm(grahami~time, data=lizards)
 # Test time by comparing with light model (dropping time)
anova(lmTL1, lmlight, test="F")
 # Test light (should be exactly the same test as in summary)
anova(lmTL1, lmtime, test="F")
# In this simple case, drop1 should do exactly the same thing we did above
drop1(lmTL1, test="F")
```

== Simple model ==

<source-file filename="variable.R" display="link">
print(summary(lmTL1))

lmlight <- lm(grahami~light, data=lizards)

lmtime <- lm(grahami~time, data=lizards)

# Test time by comparing with light model (dropping time)
anova(lmTL1, lmlight, test="F")

# Test light (should be exactly the same test as in summary)
anova(lmTL1, lmtime, test="F")

# In this simple case, drop1 should do exactly the same thing we did above

drop1(lmTL1, test="F")
</source-file>

<project-file filename="variable.Rout"/>

== Interaction model ==

<source-file filename="intvar.R" display="source">
print(summary(lmTL2))

# Test time by comparing with light model (drop time AND interaction)
anova(lmTL2, lmlight, test="F")

# Test light
anova(lmTL2, lmtime, test="F")

# Drop 1 now tests the whole interaction, also very useful

drop1(lmTL2, test="F")
</source-file>

<project-file filename="intvar.Rout"/>

= Multiple comparisons =

Some notes on the theory behind [[multiple comparisons]].

Multiple comparisons are tricky, and you probably don't need to do them.  Unlike variable-level tests, they will depend on how you parameterize your model.  Your results for a given multi-level variable can even depend on how you parameterize other variables.

<source-file filename="multcomp.mk" display="source">
multcomp.Rout: contrasts2.RData multcomp.R
</source-file>

<source-file filename="multcomp.R" display="source">
library(multcomp)

print(mc <- glht(lmTL1, linfct=mcp(time="Tukey")))

cld(mc)
</source-file>

<project-file filename="multcomp.Rout"/>

